'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require ui';
'require validation';

var callImport = rpc.declare({
	object: 'luci.trusttunnel', method: 'import_config', params: [ 'text' ]
});
var callCatalog = rpc.declare({
	object: 'luci.trusttunnel', method: 'catalog', params: [ 'refresh' ]
});
var callService = rpc.declare({
	object: 'luci.trusttunnel', method: 'service', params: [ 'action' ]
});

// Форматы под другие движки бэкенд уже отфильтровал; оставшиеся имена
// показываем как есть, чтобы не расходиться с содержимым репозитория.
function isSubnet(path) {
	return path.indexOf('Subnets/') === 0;
}

// Все настройки собраны на ОДНОЙ странице с вкладками, а не разложены по
// отдельным пунктам меню. Причина не в экономии: в LuCI каждый пункт меню —
// это отдельная страница, и переход между ними перезагружает всю оболочку
// целиком. Настройка пакета — это один сеанс работы (задать сервер, выбрать
// списки, добавить свои домены), и разрывать его тремя перезагрузками
// неправильно. Штатные страницы LuCI устроены так же: «Система» держит пять
// вкладок в одной странице, «DHCP и DNS» и «Интерфейсы» — тоже.
//
// Механизм: m.tabbed = true превращает каждую секцию в вкладку, а её заголовок
// становится названием вкладки. Переключение происходит в браузере, без запроса
// к роутеру.
return view.extend({
	load: function() {
		return Promise.all([
			uci.load('trusttunnel'),
			// Каталог нужен для вкладки «Списки». С суточным кэшем на диске
			// это чтение локального файла (замерено: меньше 100 мс), к GitHub
			// обращение раз в сутки — поэтому загружать его при открытии
			// страницы целиком приемлемо.
			callCatalog(false).catch(function(e) { return { error: e.message }; })
		]);
	},

	handleImport: function() {
		var ta = E('textarea', {
			'rows': 14, 'style': 'width:100%',
			'placeholder': _('Paste the endpoint configuration generated by your server')
		});
		ui.showModal(_('Import endpoint configuration'), [
			E('p', {}, _('Accepts both forms a server hands out: the configuration file text and a tt:// link. Nothing is saved until you press Save & Apply.')),
			ta,
			E('div', { 'class': 'right' }, [
				E('button', { 'class': 'btn', 'click': ui.hideModal }, _('Cancel')),
				' ',
				E('button', {
					'class': 'cbi-button cbi-button-positive',
					'click': ui.createHandlerFn(this, function() {
						return callImport(ta.value).then(function(res) {
							if (res.error) {
								ui.addNotification(null, E('p', {}, res.error), 'danger');
								return;
							}
							if (res.hostname)
								uci.set('trusttunnel', 'endpoint', 'hostname', res.hostname);
							if (res.username)
								uci.set('trusttunnel', 'endpoint', 'username', res.username);
							if (res.password)
								uci.set('trusttunnel', 'endpoint', 'password', res.password);
							if (res.certificate)
								uci.set('trusttunnel', 'endpoint', 'certificate', res.certificate);
							if (res.addresses && res.addresses.length)
								uci.set('trusttunnel', 'endpoint', 'address', res.addresses);

							// uci.set() держит изменения только в памяти
							// браузера. Перезагрузка страницы их выбрасывает,
							// поэтому прежний вариант (set + location.reload)
							// показывал «импортировано», а через 800 мс молча
							// возвращал прежние значения — импорт выглядел
							// работающим и не работал.
							//
							// uci.save() отправляет изменения на роутер как
							// ОТЛОЖЕННЫЕ: конфиг не применяется, службы не
							// перезапускаются, LuCI показывает «есть
							// несохранённые изменения». После перезагрузки
							// страницы поля показывают импортированное, а
							// применяет их пользователь сам — то есть условие
							// «импорт ничего не применяет» соблюдено.
							return uci.save().then(function() {
								ui.hideModal();
								ui.addNotification(null, E('p', {},
									_('Imported. Review the fields and press Save & Apply.')), 'info');
								window.setTimeout(function() { location.reload(); }, 800);
							});
						}).catch(function(e) {
							ui.addNotification(null, E('p', {}, e.message || String(e)), 'danger');
						});
					})
				}, _('Import'))
			])
		]);
	},

	handleUpdateLists: function() {
		ui.showModal(_('Please wait'), [
			E('p', { 'class': 'spinning' }, _('Downloading the lists and regenerating the rules…'))
		]);
		return callService('update_lists').then(function(res) {
			ui.hideModal();
			ui.addNotification(null, E('pre', {}, res.output || _('Done')),
				res.code === 0 ? 'info' : 'warning');
		}).catch(function(e) {
			ui.hideModal();
			ui.addNotification(null, E('p', {}, e.message), 'danger');
		});
	},

	handleRefreshCatalog: function() {
		ui.showModal(_('Please wait'), [
			E('p', { 'class': 'spinning' }, _('Refreshing the catalog from GitHub…'))
		]);
		return callCatalog(true).then(function() {
			ui.hideModal();
			location.reload();
		}).catch(function(e) {
			ui.hideModal();
			ui.addNotification(null, E('p', {}, e.message), 'danger');
		});
	},

	renderCatalog: function(catalog) {
		if (catalog.error)
			return E('div', { 'class': 'alert-message warning' }, [
				E('p', {}, _('The list catalog could not be loaded, so the choices below are unavailable.')),
				E('p', {}, catalog.error),
				E('p', {}, _('Already selected lists keep working — they are stored on the router.'))
			]);

		var selectedSources = L.toArray(uci.get('trusttunnel', 'lists', 'source'));
		var selectedSubnets = L.toArray(uci.get('trusttunnel', 'lists', 'subnet'));
		var self = this;
		this.checkboxes = [];

		var groups = (catalog.groups || []).map(function(g) {
			var items = g.files.map(function(f) {
				var subnet = isSubnet(f.path);
				var list = subnet ? selectedSubnets : selectedSources;
				var cb = E('input', {
					'type': 'checkbox',
					'data-path': f.path,
					'data-kind': subnet ? 'subnet' : 'source'
				});
				if (list.indexOf(f.path) >= 0)
					cb.checked = true;
				self.checkboxes.push(cb);
				var name = f.path.split('/').pop().replace(/\.lst$/, '');
				return E('label', {
					'style': 'display:inline-block;min-width:17em;margin:.15em 0'
				}, [ cb, ' ', name, ' ',
					E('span', { 'style': 'opacity:.6' },
						Math.round(f.size / 1024) + ' KiB') ]);
			});
			return E('div', { 'style': 'margin-bottom:.9em' }, [
				E('strong', {}, g.name),
				E('div', { 'style': 'margin-top:.2em' }, items)
			]);
		});

		if (catalog.stale)
			groups.unshift(E('div', { 'class': 'alert-message warning' },
				_('GitHub is unreachable, so this catalog is the last cached copy. Newly published lists may be missing.')));

		if (!groups.length)
			groups.push(E('em', {}, _('The catalog is empty.')));

		return E('div', {}, groups);
	},

	handleSaveApply: function(ev, mode) {
		this.collect();
		return this.super('handleSaveApply', [ ev, mode ]);
	},

	handleSave: function(ev) {
		this.collect();
		return this.super('handleSave', [ ev ]);
	},

	collect: function() {
		// Если каталог не загрузился (нет сети и нет кэша), чекбоксы не
		// строились и this.checkboxes не определён. Отсутствие данных не
		// значит "ничего не выбрано": без этой проверки Save затирал бы
		// ранее сохранённые lists.source/lists.subnet пустыми массивами
		// каждый раз, когда GitHub недоступен, — молчаливая потеря выбора
		// пользователя из-за временной сетевой проблемы.
		if (!this.checkboxes)
			return;

		var sources = [], subnets = [];
		this.checkboxes.forEach(function(cb) {
			if (!cb.checked) return;
			if (cb.getAttribute('data-kind') === 'subnet')
				subnets.push(cb.getAttribute('data-path'));
			else
				sources.push(cb.getAttribute('data-path'));
		});
		// Пустой список выражается УДАЛЕНИЕМ опции, а не пустым значением.
		// `uci set` с пустым массивом ubus отвергает — проверено прямым
		// вызовом: `{"subnet":[]}` отвечает «Invalid argument». Именно это и
		// ломало сохранение, когда не выбрано ни одной подсети: форма падала
		// с «RPC call to uci/set failed with ubus code 2».
		//
		// Пустая строка здесь безопаснее null по смыслу и делает то же: в
		// uci.js ветка удаления срабатывает на обоих, причём удаление
		// записывается ТОЛЬКО если опция есть в загруженном состоянии, так что
		// на отсутствующей это ничего не отправляет.
		uci.set('trusttunnel', 'lists', 'source', sources.length ? sources : '');
		uci.set('trusttunnel', 'lists', 'subnet', subnets.length ? subnets : '');
	},

	render: function(data) {
		var catalog = data[1];
		var m, s, o;

		m = new form.Map('trusttunnel', _('TrustTunnel'));
		// Каждая секция становится вкладкой. Прецедент в штатных страницах:
		// network/dhcp, network/interfaces, network/routes, system/flash.
		m.tabbed = true;

		// --- Общее -----------------------------------------------------------
		s = m.section(form.NamedSection, 'main', 'main', _('General'));

		o = s.option(form.Flag, 'enabled', _('Start on boot'),
			_('Whether the service starts when the router boots. The Start button on the Status page runs it right now.'));
		o.rmempty = false;

		o = s.option(form.ListValue, 'mode', _('Mode'));
		o.value('selective', _('Bypass by list — only listed domains go through the tunnel'));
		o.value('full', _('Everything through VPN — all LAN traffic goes through the tunnel'));
		o.description = _('In "bypass by list" mode dnsmasq puts the addresses of listed domains into an nftables set, and only those are routed into the tunnel. In "everything through VPN" mode the lists are not used and exceptions are handled by the client itself.');

		o = s.option(form.Flag, 'full_exclude_lists',
			_('Send the selected lists out directly'),
			_('In "everything through VPN" mode, hand the domains from the selected lists to the client as exclusions. Thousands of entries increase memory use.'));
		o.depends('mode', 'full');

		o = s.option(form.ListValue, 'log_level', _('Log level'));
		o.value('info', 'info');
		o.value('debug', 'debug');
		o.value('trace', 'trace');
		o.description = _('debug and trace write a lot; leave them on only while investigating something.');

		// --- Сервер ----------------------------------------------------------
		s = m.section(form.NamedSection, 'endpoint', 'endpoint', _('Server'));

		o = s.option(form.Button, '_import', _('Server configuration'),
			_('The fast path: paste what your server generated and the fields below fill themselves in.'));
		o.inputtitle = _('Import…');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleImport');

		o = s.option(form.DynamicList, 'address', _('Addresses'),
			_('host:port or [ipv6]:port. With several addresses the client measures them and picks the fastest.'));
		o.placeholder = '203.0.113.10:443';
		o.rmempty = false;

		o = s.option(form.Value, 'hostname', _('TLS host name'),
			_('Used for the TLS session, not for routing. Without it many servers refuse the connection.'));
		o.datatype = 'hostname';
		o.rmempty = false;

		o = s.option(form.Value, 'username', _('User name'));
		o.rmempty = false;

		o = s.option(form.Value, 'password', _('Password'));
		o.password = true;
		o.rmempty = false;

		o = s.option(form.ListValue, 'protocol', _('Transport'));
		o.value('http2', 'HTTP/2');
		o.value('http3', 'HTTP/3 (QUIC)');
		o.description = _('QUIC is often faster, but some networks throttle or block UDP.');

		o = s.option(form.Flag, 'anti_dpi', _('Anti-DPI'),
			_('Countermeasures against traffic inspection. Worth enabling if the connection establishes but keeps dropping.'));

		o = s.option(form.Flag, 'post_quantum', _('Post-quantum key exchange'));
		o.default = '1';

		o = s.option(form.Flag, 'has_ipv6', _('Server carries IPv6'));
		o.default = '1';

		o = s.option(form.Flag, 'skip_verification', _('Skip certificate verification'),
			_('Accepts any certificate, which removes the protection against a substituted server. Pin the certificate below instead whenever you can.'));

		o = s.option(form.TextValue, 'certificate', _('Pinned certificate (PEM)'),
			_('Leave empty to use the system trust store, which requires the ca-bundle package.'));
		o.rows = 6;
		o.optional = true;

		// Два поля про DNS легко спутать, поэтому каждое говорит, КТО спрашивает,
		// и прямо отрицает чужую роль. Проверено опытом на живом роутере: если
		// подставить в «DNS для доменов из списков» заведомо мёртвый адрес,
		// резолвинг обходных доменов истекает по таймауту — значит запросы идут
		// именно туда, а DNS-прокси клиента их не перехватывает. То есть на
		// обход эти два поля влияют по-разному, и путать их нельзя.
		o = s.option(form.DynamicList, 'dns_upstream', _('DNS used by the client itself'),
			_('Applies to what the TrustTunnel client resolves on its own — for example the exclusion domains it pre-resolves. This is NOT the resolver for domains from the lists: those are resolved by the router, see the Network tab. Empty means the client default, AdGuard DNS unfiltered.'));
		o.placeholder = 'tls://1.1.1.1';
		// Форматы взяты из эталонного конфига, который генерирует сам
		// setup_wizard: обычный DNS, tcp://, tls://, https://, quic:// и
		// sdns://. Предустановки — готовые строки этих форматов; своё значение
		// вписывается тут же, список их не ограничивает.
		o.value('tls://1.1.1.1', 'Cloudflare — DNS over TLS');
		o.value('tls://9.9.9.9', 'Quad9 — DNS over TLS');
		o.value('tls://dns.adguard-dns.com', 'AdGuard — DNS over TLS');
		o.value('https://cloudflare-dns.com/dns-query', 'Cloudflare — DNS over HTTPS');
		o.value('https://dns.quad9.net/dns-query', 'Quad9 — DNS over HTTPS');
		o.value('quic://dns.adguard-dns.com', 'AdGuard — DNS over QUIC');
		o.value('1.1.1.1:53', 'Cloudflare — ' + _('plain DNS'));
		o.value('9.9.9.9:53', 'Quad9 — ' + _('plain DNS'));

		// --- Списки ----------------------------------------------------------
		s = m.section(form.NamedSection, 'lists', 'lists', _('Lists'));
		s.description = _('Community lists from itdoginfo/allow-domains. The catalog comes from GitHub, so lists published upstream appear here without a package update.');

		// Каталог — не поле формы, а произвольная разметка с чекбоксами,
		// поэтому renderWidget подменяется у экземпляра опции: так блок
		// попадает ВНУТРЬ вкладки, а не под форму, где он был бы виден на
		// всех вкладках сразу.
		o = s.option(form.DummyValue, '_catalog', _('Available lists'));
		o.renderWidget = L.bind(function() {
			return this.renderCatalog(catalog);
		}, this);
		// write и remove ОБЯЗАТЕЛЬНО заглушены. form.DummyValue переопределяет
		// только отрисовку, а запись в UCI наследует от form.Value: сохранение
		// вызывает у каждой опции write() или remove(). Штатный DummyValue
		// прячет значение в скрытое поле, и запись просто возвращает его на
		// место, но здесь отрисовка подменена своей разметкой — скрытого поля
		// нет, formvalue пустой, и уходил `uci set` с пустым аргументом. Форма
		// падала с «RPC call to uci/set failed with ubus code 2: Invalid
		// argument». Плюс сама опция не настройка: `_catalog` не должен
		// появиться в /etc/config/trusttunnel ни при каких условиях.
		o.write = function() {};
		o.remove = function() {};

		o = s.option(form.DynamicList, 'url', _('Your own list URLs'),
			_('Any URL returning one domain per line. Downloaded alongside the community lists.'));
		o.placeholder = 'https://example.org/my-domains.lst';

		o = s.option(form.Flag, 'auto_update', _('Update automatically'),
			_('A cron job refreshes the selected lists once a day at 04:17.'));
		o.default = '1';

		o = s.option(form.Button, '_update', _('Update now'),
			_('Downloads the selected lists and regenerates the rules immediately. Saved changes are used, so save first.'));
		o.inputtitle = _('Update lists');
		o.inputstyle = 'apply';
		o.onclick = ui.createHandlerFn(this, 'handleUpdateLists');

		o = s.option(form.Button, '_refresh', _('Catalog'),
			_('Re-reads the list of available files from GitHub. The catalog is cached for a day.'));
		o.inputtitle = _('Refresh catalog');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleRefreshCatalog');

		// --- Свои домены -----------------------------------------------------
		s = m.section(form.NamedSection, 'domains', 'domains', _('My domains'));
		s.description = _('Your own two lists. They are applied on top of the community lists.');

		o = s.option(form.DynamicList, 'bypass', _('Bypass these'),
			_('Sent through the tunnel in addition to the selected lists. One domain per entry; subdomains are matched automatically.'));
		o.placeholder = 'example.com';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var v = value.toLowerCase();
			// usr/libexec/trusttunnel/normalize отбрасывает голый IPv4 из
			// списка доменов (это данные не того рода) до проверки на
			// синтаксис домена. Без этой же проверки здесь строка вида
			// "192.168.1.1" проходит валидацию формы как "домен" (цифровые
			// метки допустимы синтаксически), сохраняется в UCI, а генератор
			// молча её отбрасывает — пользователь видит "сохранено", но
			// правило никогда не появляется.
			if (/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/.test(v))
				return _('Not a valid domain name');
			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Not a valid domain name');
			return true;
		};

		o = s.option(form.DynamicList, 'direct', _('Do not bypass these'),
			_('Always sent out directly, even when a community list or a shared CDN address would otherwise route them through the tunnel. Accepts a domain, *.domain, an IP address or a CIDR range.'));
		o.placeholder = 'bank.example';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var v = value.toLowerCase();
			if (/^\*\./.test(v)) v = v.slice(2);
			if (/^[0-9a-f:.\/]+$/.test(v)) return true;
			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Not a valid domain, IP address or CIDR range');
			return true;
		};

		// --- Сеть ------------------------------------------------------------
		s = m.section(form.NamedSection, 'network', 'network', _('Network'));
		s.description = _('These rarely need changing. MTU is the exception: too high a value makes small pages load while TLS handshakes and large downloads stall.');

		// Поля «устройство TUN» здесь БОЛЬШЕ НЕТ. Имя устройства выбирает сам
		// клиент, а не мы: ключей для его задания в схеме клиента не существует.
		// Оставлять поле означало бы предлагать настройку, которая ни на что не
		// влияет. Фактическое имя показано на странице состояния.
		o = s.option(form.Value, 'mtu', _('MTU'));
		o.datatype = 'range(576,9000)';
		o.default = '1350';

		o = s.option(form.Value, 'lan_devices', _('LAN interfaces'),
			_('Space-separated list whose forwarded traffic is considered. Empty means the device of the lan network.'));
		o.placeholder = 'br-lan';
		o.optional = true;

		o = s.option(form.Flag, 'blackhole_on_down', _('Drop traffic when the tunnel is down'),
			_('Adds a blackhole route so marked traffic is dropped instead of leaking to the provider.'));
		o.default = '1';

		o = s.option(form.Flag, 'include_router_traffic', _('Route the router\'s own traffic too'),
			_('By default only forwarded LAN traffic is routed. Enabling this also routes traffic originated by the router itself, including list updates and the update check.'));
		// Один селектор вместо прежней пары «флаг + адрес». Флаг «резолвить
		// через туннель» и тип резолвера могли противоречить друг другу — это
		// та же путаница, из-за которой два поля DNS приходилось разводить
		// описаниями. Теперь режим один, и от него зависит, какие поля видны.
		//
		// Межсекционный depends() в form.js не поддерживается, поэтому
		// применимость к режиму «обход по списку» указана в описании.
		// Генераторы эти опции в режиме «всё через VPN» игнорируют.
		o = s.option(form.ListValue, 'list_dns', _('DNS for domains from the lists'),
			_('Applies in "bypass by list" mode only. Who resolves the domains from your lists, and how the query is protected.'));
		o.value('plain', _('Plain DNS through the tunnel — the query is hidden by the tunnel itself'));
		o.value('doh', _('Encrypted DNS over HTTPS — a local proxy, the query goes out encrypted'));
		o.value('provider', _('Whatever the router already uses — usually the provider'));
		o.default = 'plain';

		o = s.option(form.Value, 'list_resolver', _('Plain resolver address'),
			// Честно про ограничение: значение уходит в директиву dnsmasq
			// `server=/домен/адрес`, а она принимает только обычный адрес.
			// Защита устроена иначе, и это стоит сказать: адрес резолвера
			// помещается в набор обхода (gen-lists), поэтому запрос идёт
			// ВНУТРИ туннеля, и провайдер не видит его и не может подменить.
			_('This address is placed in the bypass set, so the query travels inside the tunnel and the provider can neither read nor spoof it. A port may be added after #.'));
		// НЕ datatype='ipaddr': директива dnsmasq принимает `адрес#порт`, и без
		// порта нельзя указать локальный прокси, который слушает не на 53.
		o.default = '1.1.1.1';
		o.depends('list_dns', 'plain');
		o.validate = function(section_id, value) {
			if (!value) return true;
			var host = value, port = null, hash = value.indexOf('#');
			if (hash >= 0) {
				host = value.slice(0, hash);
				port = value.slice(hash + 1);
				if (!/^[0-9]{1,5}$/.test(port) || +port < 1 || +port > 65535)
					return _('The port after # must be between 1 and 65535');
			}
			// Проверка адреса средствами LuCI, чтобы не заводить свой разбор
			// IPv4 и IPv6.
			if (!validation.parseIPv4(host) && !validation.parseIPv6(host))
				return _('Enter an IP address, optionally followed by #port');
			return true;
		};
		o.value('1.1.1.1', 'Cloudflare');
		o.value('9.9.9.9', 'Quad9');
		o.value('8.8.8.8', 'Google');
		o.value('94.140.14.14', 'AdGuard');

		o = s.option(form.Value, 'list_doh_url', _('DoH resolver URL'),
			_('The service starts a local https-dns-proxy on the router and points dnsmasq at it, so the query leaves encrypted — but directly, not through the tunnel. For NextDNS with your own profile use https://dns.nextdns.io/<your-id>. Requires the https-dns-proxy package; without it the list domains fall back to the provider resolver and Diagnostics says so.'));
		o.depends('list_dns', 'doh');
		o.placeholder = 'https://dns.quad9.net/dns-query';
		o.value('https://dns.quad9.net/dns-query', 'Quad9');
		o.value('https://cloudflare-dns.com/dns-query', 'Cloudflare');
		o.value('https://dns.adguard-dns.com/dns-query', 'AdGuard');
		o.validate = function(section_id, value) {
			if (!value) return true;
			// Только https: сам смысл настройки в шифровании, и http здесь
			// был бы обманом ожидания.
			if (!/^https:\/\/[^\s]+$/.test(value))
				return _('Enter an https:// URL');
			return true;
		};

		o = s.option(form.Value, 'list_doh_port', _('Local port for the proxy'),
			// Порт настраиваемый, а не зашитый: 5053 занимает пакетный init
			// https-dns-proxy, 5453 — stubby, и при конфликте иначе было бы
			// нечем разойтись.
			_('The local proxy listens on 127.0.0.1 at this port. Change it only if something else on the router already uses it.'));
		o.depends('list_dns', 'doh');
		o.default = '5460';
		o.datatype = 'port';

		o = s.option(form.Flag, 'intercept_dns', _('Intercept client DNS'),
			_('Applies in "bypass by list" mode only. Redirects port 53 to the router and blocks 853. Without it a device using its own DoH resolver bypasses the list matching.'));

		// Метка идёт прямо в `ip rule add fwmark …`, поэтому формат проверяем
		// здесь: без проверки мусорное значение доходит до ядра, `ip rule`
		// падает, а его stderr никуда не всплывает — маршрутизация остаётся
		// собранной наполовину и молча.
		o = s.option(form.Value, 'fwmark', _('Firewall mark'),
			_('Decimal or 0x-prefixed hexadecimal. Change only on a conflict with mwan3, SQM or another package that marks packets.'));
		o.default = '0x9527';
		o.validate = function(section_id, value) {
			if (!value) return true;
			if (!/^(0x[0-9a-fA-F]{1,8}|[0-9]{1,10})$/.test(value))
				return _('Enter a decimal number or 0x-prefixed hexadecimal');
			// Ограничение на число цифр (до 10) само по себе не отсекает
			// значение, превышающее 32-битный максимум: "9999999999" проходит
			// эту проверку по форме, хотя fwmark — 32-битное поле в ядре.
			if (!/^0x/i.test(value) && +value > 4294967295)
				return _('Enter a decimal number no greater than 4294967295');
			return true;
		};

		// НЕ range(1,252). Идентификатор таблицы маршрутизации в Linux
		// 32-битный, и значение по умолчанию 880 выбрано именно чтобы не
		// пересекаться с диапазоном, который занимают другие пакеты.
		// Проверено на живом OpenWrt: ядро принимает и 880, и 900.
		// Ограничение 1..252 отвергало бы штатную конфигурацию, то есть
		// страницу настроек нельзя было бы сохранить из коробки.
		// Исключаются только 0 и 253..255 — это main, default и local,
		// перехват которых сломал бы маршрутизацию всей системы.
		o = s.option(form.Value, 'table', _('Routing table'),
			_('Any table id except 0 and the reserved 253-255.'));
		o.datatype = 'uinteger';
		o.default = '880';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var n = +value;
			if (!/^[0-9]+$/.test(value) || n < 1 || n > 4294967294)
				return _('Enter a table id between 1 and 4294967294');
			if (n >= 253 && n <= 255)
				return _('Table ids 253, 254 and 255 are reserved by the system');
			return true;
		};

		return m.render();
	}
});
